export const SAMPLE_PATIENTS = [
  {
    index: 522,
    insurance_type: 'Medicare/Medicaid',
    label: 0,
    prev_readmit_group: 1,
    los_group: '6 to 8',
    risk_score_bin: 3,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'lower',
    age_bin: 1.0,
  },
  {
    index: 5031,
    insurance_type: 'Medicare/Medicaid',
    label: 1,
    prev_readmit_group: 2,
    los_group: '9+',
    risk_score_bin: 7,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'lower',
    age_bin: 3.0,
  },
  {
    index: 4338,
    insurance_type: 'Private',
    label: 1,
    prev_readmit_group: 2,
    los_group: '6 to 8',
    risk_score_bin: 6,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'higher',
    age_bin: 1.0,
  },
  {
    index: 170,
    insurance_type: 'Uninsured',
    label: 1,
    prev_readmit_group: 1,
    los_group: '6 to 8',
    risk_score_bin: 3,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'lower',
    age_bin: 1.0,
  },
  {
    index: 5473,
    insurance_type: 'Private',
    label: 0,
    prev_readmit_group: 1,
    los_group: '5 or less',
    risk_score_bin: 2,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'lower',
    age_bin: 1.0,
  },
  {
    index: 4512,
    insurance_type: 'Medicare/Medicaid',
    label: 1,
    prev_readmit_group: 2,
    los_group: '6 to 8',
    risk_score_bin: 7,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'higher',
    age_bin: 1.0,
  },
  {
    index: 1795,
    insurance_type: 'Medicare/Medicaid',
    label: 0,
    prev_readmit_group: 1,
    los_group: '6 to 8',
    risk_score_bin: 2,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'lower',
    age_bin: 1.0,
  },
  {
    index: 7220,
    insurance_type: 'Medicare/Medicaid',
    label: 1,
    prev_readmit_group: 2,
    los_group: '9+',
    risk_score_bin: 7,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'higher',
    age_bin: 3.0,
  },
  {
    index: 4543,
    insurance_type: 'Medicare/Medicaid',
    label: 0,
    prev_readmit_group: 1,
    los_group: '6 to 8',
    risk_score_bin: 2,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'lower',
    age_bin: 1.0,
  },
  {
    index: 1943,
    insurance_type: 'Private',
    label: 1,
    prev_readmit_group: 2,
    los_group: '6 to 8',
    risk_score_bin: 7,
    dc_location: 'HH/SNF',
    primary_dx_tier: 'higher',
    age_bin: 2.0,
  },
];
