export const SAMPLE_PATIENTS = [
  {
    insurance_type: 'Medicare/Medicaid',
    prev_readmit_group: '1 prior readmission',
    los_group: '6 to 8',
    dc_location: 'HH/SNF',
    primary_dx: 'Pneumonia',
    age_bin: '51 years or younger',
  },
  {
    insurance_type: 'Medicare/Medicaid',
    prev_readmit_group: '2 or more prior readmissions',
    los_group: '9+',
    dc_location: 'HH/SNF',
    primary_dx: 'Diabetes',
    age_bin: '68 years or older',
  },
  {
    insurance_type: 'Private',
    prev_readmit_group: '2 or more prior readmissions',
    los_group: '6 to 8',
    dc_location: 'HH/SNF',
    primary_dx: 'Sepsis',
    age_bin: '51 years or younger',
  },
  {
    insurance_type: 'Uninsured',
    prev_readmit_group: '1 prior readmission',
    los_group: '6 to 8',
    dc_location: 'HH/SNF',
    primary_dx: 'Influenza',
    age_bin: '51 years or younger',
  },
  {
    insurance_type: 'Private',
    prev_readmit_group: '1 prior readmission',
    los_group: '5 or less',
    dc_location: 'HH/SNF',
    primary_dx: 'Fracture',
    age_bin: '51 years or younger',
  },
  {
    insurance_type: 'Medicare/Medicaid',
    prev_readmit_group: '2 or more prior readmissions',
    los_group: '6 to 8',
    dc_location: 'HH/SNF',
    primary_dx: 'COPD',
    age_bin: '51 years or younger',
  },
  {
    insurance_type: 'Medicare/Medicaid',
    prev_readmit_group: '1 prior readmission',
    los_group: '6 to 8',
    dc_location: 'HH/SNF',
    primary_dx: 'Hypertension',
    age_bin: '51 years or younger',
  },
  {
    insurance_type: 'Medicare/Medicaid',
    prev_readmit_group: '2 or more prior readmissions',
    los_group: '9+',
    dc_location: 'HH/SNF',
    primary_dx: 'Heart Failure',
    age_bin: '68 years or older',
  },
  {
    insurance_type: 'Medicare/Medicaid',
    prev_readmit_group: '1 prior readmission',
    los_group: '6 to 8',
    dc_location: 'HH/SNF',
    primary_dx: 'Appendicitis',
    age_bin: '51 years or younger',
  },
  {
    insurance_type: 'Private',
    prev_readmit_group: '2 or more prior readmissions',
    los_group: '6 to 8',
    dc_location: 'HH/SNF',
    primary_dx: 'Kidney Disease',
    age_bin: '52 to 67 years',
  },
];
